version: "3.1"
services:
  pythontodoapp:
    image: abishek1710/todowebapppython:latest
    ports:
      - 5000:5000
    environment:
      - MYSQL_HOST: ${MYSQL_HOST}
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      - MYSQL_DB: todo_app
      - SECRET_KEY: ${SECRET_KEY}

volumes:
  mymysqlvolume:
    driver: local    

  mysqldb:
    image: mysql:oraclelinux9
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mymysqlvolume: /var/lib/mysql
